<a href="https://colab.research.google.com/github/sujithh1110/AIML11/blob/main/lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
inputs =[1,2,3]
weights=[0.2,0.3,-0.5]
bias=2

output=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias
print(output)

1.3


In [10]:
inputs=[0.4,0.3,1,0.8]
weights1=[0.3,0.2,0.1,0.4]
weights2=[0.4,0.1,-0.1,0.2]
weights3=[0.2,-0.2,-0.1,0.8]

bias1=0.5
bias2=0.3
bias3=0.6

output=[inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights1[3]+bias1,
        inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+inputs[3]*weights2[3]+bias2,
        inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights3[3]+bias3,]

print(output)

[1.1, 0.55, 1.1600000000000001]


In [12]:
import numpy as np
inputs=np.array([0.4,0.3,1,0.8])

weights=np.array([
    [0.3,0.2,0.1,0.4],
    [0.4,0.1,-0.1,0.2],
    [0.2,-0.2,-0.1,0.8]
])

biases=np.array([0.5,0.3,0.6])

output=np.dot(weights,inputs)+biases

print(output)




[1.1  0.55 1.16]


In [17]:
import numpy as np
def relu(x):
  return np.maximum(0,x)
  inputs=np.array([0.4,0.3,1,0.8])
  weights=np.array([
    [0.3,0.2,0.1,0.4],
    [0.4,0.1,-0.1,0.2],
    [0.2,-0.2,-0.1,0.8]
])
biases=np.array([0.5,0.3,0.6])
output=np.dot(weights,inputs)+biases

output=relu(output)
print(output)


[1.1  0.55 1.16]


NameError: name 'sigmoid' is not defined

In [18]:
import numpy as np
def sigmoid(x):
  return 1/(1+np.exp(-x))
  def relux(x):
    return np.maximum(0,x)
  inputs=np.array([0.4,0.3,1,0.8])
  weights=np.array([
    [0.3,0.2,0.1,0.4],
    [0.4,0.1,-0.1,0.2],
    [0.2,-0.2,-0.1,0.8]
])
biases=np.array([0.5,0.3,0.6])
output=np.dot(weights,inputs)+biases
output1=relu(output)
print(output1)
output2=sigmoid(output)
print(output2)



[1.1  0.55 1.16]
[0.75026011 0.63413559 0.76133271]
